### PR TITLE
relay-application: expose sink and source URIs as D-Bus properties

### PR DESCRIPTION
**Pull request by xhaakon**

### CODE REVIEW

**Review by justinjoy — COMMENTED** [review]
I am not sure which use case requires to access {sink,source} uri via D-Bus?

**Comment by xhaakon** [comment]
> I am not sure which use case requires to access {sink,source} uri via D-Bus?

I 'm reading those URIs in an upcoming test case for stream disconnect operator APIs and use them to create test sender and receiver.

D-Bus property seemed like the cleanest way to expose the URIs and I guess it could also be useful for the operator or the applications that communicate with relay agent via D-Bus to have access to them.

Do you see any security or another problem in exposing those values locally on D-Bus? If so I may find another way to get to the values that doesn't involve leaking them to other processes.

This is the new test case in question: https://github.com/hwangsaeul/gaeul/pull/51/commits/48f4679ac3f20d1de86e56bd48d7a7db9f4d17c2

**Comment by justinjoy** [comment]
> Do you see any security or another problem in exposing those values locally on D-Bus? 

No, I don't have security concerns, but just thought that local processes could get the information by parsing the settings file.

**Review by justinjoy — APPROVED** [review]

**Comment by xhaakon** [comment]
> just thought that local processes could get the information by parsing the settings file.

Thinking of that, using `/etc/gaeul2/gaeul2.ini` isn't mandatory and your relay process can load settings from anywhere you tell it to with `-c` parameter. Especially if you should decide to run several relay processes on one node, each will have to have its own set ports and thus config file.

So it seems better after all if you can directly ask a relay process about its URIs rather than make guesses about where its configuration  came from.

**Comment by justinjoy** [comment]
I see your point and totally agreed. 👍🏻

**Pull request merged**
